### ISSUE TITLE
Sysmon hangs when deleting large files on USB-devices

### ISSUE THREAD

**Issue by SysmonMike** [MicrosoftDocs/sysinternals#628] opened 2022-11-17 20:06 UTC
When deleting large files located on USB-devices Sysmon "hangs" and the file is never deleted until Sysmon is killed.

I'm using the latest version of Sysmon (v14.12) and the problem seems to start with files larger than about 1.1 GB.
Deleting files of sizes 1.03 GB, 969 MB, and 619 MB all works but is a bit slower than usual.

Sizes like 1.1 GB and 1.4 GB doesn't work and the error messages shown below are displayed:
![Sysmon_delete_1 1GB](https://user-images.githubusercontent.com/86366661/202547807-8e0f0c48-8712-43ab-a68b-8915ec7d548e.png)

![Sysmon_delete_1 4GB](https://user-images.githubusercontent.com/86366661/202547840-ac085593-6ce3-4046-952b-a9c6178dc1df.png)

If I select Try Again the same error message is shown again, and again, ...

I guess this is a bug!?

**Comment by foxmsft** [comment] 2022-11-17 20:28
What filesystem is there on that drive?

**Comment by SysmonMike** [comment] 2022-11-18 07:42
The USB is a FAT32 drive.
![Drive_1](https://user-images.githubusercontent.com/86366661/202648074-e5c64eeb-096e-45d5-9dd7-bda37a857e00.png)

**Comment by marcuswestlund** [comment] 2022-11-18 09:07
> When deleting large files located on USB-devices Sysmon "hangs" and the file is never deleted until Sysmon is killed.
> 
> I'm using the latest version of Sysmon (v14.12) and the problem seems to start with files larger than about 1.1 GB. Deleting files of sizes 1.03 GB, 969 MB, and 619 MB all works but is a bit slower than usual.
> 
> Sizes like 1.1 GB and 1.4 GB doesn't work and the error messages shown below are displayed: ![Sysmon_delete_1 1GB](https://user-images.githubusercontent.com/86366661/202547807-8e0f0c48-8712-43ab-a68b-8915ec7d548e.png)
> 
> ![Sysmon_delete_1 4GB](https://user-images.githubusercontent.com/86366661/202547840-ac085593-6ce3-4046-952b-a9c6178dc1df.png)
> 
> If I select Try Again the same error message is shown again, and again, ...
> 
> I guess this is a bug!?

I can add that this issue has been there since at least since Sysmon 12.03 (x64).

**Comment by foxmsft** [comment] 2022-11-25 14:20
What are the steps to reproduce this? Deletes from slower drives do take longer (due to the data being read for checksums before), but eventually they do complete.

Does this "The action can't be completed" dialog pop up as soon as shift-del is issued?
Are there other Sysmon events besides `FileDelete` involved?

**Comment by SysmonMike** [comment] 2022-11-27 10:29
@foxmsft I don't think it is a question of slow drives or me being impatient. When the "action can't be completed" appears I am unable to delete the file(s). I can retry about 10 times and the file is still not deleted. I've tried both small USB-memory sticks and larger USB 3 hard drives and neither of them are "slow".

Deleting files with SHIFT+DEL is the most troublesome. For larger files the error message always seem to appear. Deleting with DEL only (i.e. "via" the Recycle bin) works much better but usually results in an error message for the last file deleted from the Recycle bin. Note that the file size here is reported as 0 bytes!

![image](https://user-images.githubusercontent.com/86366661/204129583-6fe93dd6-8fee-4e8f-bebc-e7bc22b093e7.png)

I tried running Sysmon with an empty config file (logging no events what so ever) I was able to get the zero size error message above on one single occasion when emptying the Recycle bin!?

The event in question isn't `FileDelete ` (EID 23) but rather `FileDeleteDetected` (EID 26). 
The rule that matches my large test files in the one:

`<TargetFilename name="FileDeleteDetected - Container file deleted" condition="end with">.iso</TargetFilename>`

I hope this gives you enough information to investigate further.

**Comment by SysmonMike** [comment] 2022-11-27 10:36
Sorry, I forgot. The delay between SHIFT+DEL and the error message is about 8-10 seconds.

**Comment by foxmsft** [comment] 2022-11-28 19:03
This is exactly what I needed to know, thank you! I'll get back here with an update.

**Comment by foxmsft** [comment] 2022-12-07 13:34
@SysmonMike do you have other relevant bits of the config to share? I can't get this to repro with either SSD or spindle exFAT USB storage.

I'm interested in the `HashAlgorithms` directive or anything else that might be relevant here.
Thanks!

**Comment by SysmonMike** [comment] 2022-12-08 16:41
@foxmsft, We have set the hashes to all hash types in the config file like this:
`<HashAlgorithms>*</HashAlgorithms> `

I don't think it matters but we have also changed the archive directory:
`<ArchiveDirectory>Sysmon_Deleted_Files</ArchiveDirectory>`

And finally, I doubt that it matters but we log all file creations (EID 11) on USB-devices with rules like these:
`
<TargetFilename name="Technique_id=T1052.001,Sub_Technique_name=Exfiltration over USB,Technique_name=Exfiltration Over Physical Medium,Tactic=Exfiltration" condition="begin with">D:\</TargetFilename>
<TargetFilename name="Technique_id=T1052.001,Sub_Technique_name=Exfiltration over USB,Technique_name=Exfiltration Over Physical Medium,Tactic=Exfiltration" condition="begin with">E:\</TargetFilename>`

**Comment by SysmonMike** [comment] 2022-12-09 07:49
@foxmsft, I seems that the problem is indeed related to the HashAlgo configuration. 

I changed the configuration to;
`<HashAlgorithms>SHA1,IMPHASH</HashAlgorithms>`
and now it works better (but unfortunately not perfect).
I still get the error message, but if I press retry I'm able to delete the file(s) in 1 or 2 retries.

**Comment by foxmsft** [comment] 2022-12-09 13:04
Does this still happen for you with just `FileDeleteDetected`? Did you find the minimal config where this behavior can be observed?

```xml
<Sysmon schemaversion="4.83">
  <HashAlgorithms>*</HashAlgorithms>
  <ArchiveDirectory>Sysmon_Deleted_Files</ArchiveDirectory>
    
  <EventFiltering>
    <ProcessCreate onmatch="include" />
    <ProcessTerminate onmatch="include" />

      <FileDeleteDetected onmatch="include">
        <TargetFilename name="FileDeleteDetected - Container file deleted" condition="end with">.iso</TargetFilename>
      </FileDeleteDetected>
  </EventFiltering>
</Sysmon>

```

**Comment by SysmonMike** [comment] 2022-12-09 15:43
@foxmsft I tried the config above at it works fine. No errors are displayed when deleting large files.

**Comment by foxmsft** [comment] 2022-12-09 15:45
Now it's a matter of figuring out which 2 or more rules interact to create this situation. Can you share the full config?

**Comment by SysmonMike** [comment] 2022-12-09 15:50
Unfortunately I can't do that. Company policy... I can share pieces but not the entire file.

And figuring out the combination of rules might be tricky since the config file is rather large (almost 7 000 lines).

Any suggestions what to try next or where to start looking for "culprit" rules?

**Comment by SysmonMike** [comment] 2022-12-11 17:41
@foxmsft I've managed to identify a minimal configuration file that causes the problematic situation:

```
<Sysmon schemaversion="4.83">
    <HashAlgorithms>*</HashAlgorithms> 
    <EventFiltering> 
        <!-- Event ID 1: Process creation -->
        <ProcessCreate onmatch="include" />

        <!-- Event ID 5: Process terminated -->
        <ProcessTerminate onmatch="include" />

        <!-- Event ID 23: FileDelete (A file delete was detected) -->
        <RuleGroup name="FileDelete - Exclude" groupRelation="or">
            <FileDelete onmatch="exclude">
                <!-- MD5 of __PSScriptPolicyTest_RANDOM.ps1 file -->
                <Hashes condition="contains">D17FE0A3F47BE24A6453E9EF58C94641</Hashes>
            </FileDelete>
        </RuleGroup>

        <!-- Event ID 26: FileDeleteDetected (File Delete logged)  -->
        <RuleGroup name="FileDeleteDetected - Include" groupRelation="or">
            <FileDeleteDetected onmatch="include">
                <TargetFilename name="FileDeleteDetected - Container file" condition="end with">.iso</TargetFilename>
            </FileDeleteDetected>
        </RuleGroup>

    </EventFiltering>
</Sysmon>
```

**Comment by foxmsft** [comment] 2022-12-15 11:51
Thanks for all the support, fix is incoming :)

**Comment by marcuswestlund** [comment] 2022-12-15 20:17
> Thanks for all the support, fix is incoming :)

Great work @foxmsft and @SysmonMike !

**Comment by foxmsft** [comment] 2023-02-02 19:12
Latest version, v14.14 should fix this behavior. There are some performance improvements around the file events, upcoming in the near future.

**Closed by foxmsft** 2023-02-02 19:12 UTC
