### ISSUE TITLE
BSOD after sysmon installed

### ISSUE THREAD

**Issue by yoannwyffels** [MicrosoftDocs/sysinternals#223] opened 2019-07-05 09:27 UTC
BSOD upcoming just after sysmon installed. Sysmon drive name is "**psav3cld.sys**"
I can provide the full memory dump if you need it ?

### SYSTEM_SCAN_AT_RAISED_IRQL_CAUGHT_IMPROPER_DRIVER_UNLOAD (d4)
A driver unloaded without cancelling lookaside lists, DPCs, worker threads, etc.
The broken driver's name is displayed on the screen and saved in
KiBugCheckDriver.
When possible, the guilty driver's name (Unicode string) is printed on
the bugcheck screen and saved in KiBugCheckDriver.
An attempt was made to access the driver at raised IRQL after it unloaded.
If kernel debugger is available get stack backtrace.
Arguments:
Arg1: fffff8075e1abae0, memory referenced
Arg2: 0000000000000002, IRQL
Arg3: 0000000000000000, value 0 = read operation, 1 = write operation
Arg4: fffff8074eb48200, address which referenced memory

Debugging Details:
------------------

DUMP_CLASS: 1

DUMP_QUALIFIER: 402

BUILD_VERSION_STRING:  17763.1.amd64fre.rs5_release.180914-1434

SYSTEM_MANUFACTURER:  HP

SYSTEM_PRODUCT_NAME:  HP Pro x2 612 G2

SYSTEM_SKU:  X4C20AV

BIOS_VENDOR:  HP

BIOS_VERSION:  P86 Ver. 01.16

BIOS_DATE:  03/29/2018

BASEBOARD_MANUFACTURER:  HP

BASEBOARD_PRODUCT:  828B

BASEBOARD_VERSION:  KBC Version 48.61

DUMP_TYPE:  0

BUGCHECK_P1: fffff8075e1abae0

BUGCHECK_P2: 2

BUGCHECK_P3: 0

BUGCHECK_P4: fffff8074eb48200

FAULTING_IP: 
**psav3cld.sys**+1bae0
fffff807`5e1abae0 ??              ???

CPU_COUNT: 4

CPU_MHZ: 648

CPU_VENDOR:  GenuineIntel

CPU_FAMILY: 6

CPU_MODEL: 8e

CPU_STEPPING: 9

CPU_MICROCODE: 6,8e,9,0 (F,M,S,R)  SIG: 84'00000000 (cache) 84'00000000 (init)

DEFAULT_BUCKET_ID:  CODE_CORRUPTION

BUGCHECK_STR:  0xD4

PROCESS_NAME:  svchost.exe

CURRENT_IRQL:  2

ANALYSIS_SESSION_HOST:  B1025041

ANALYSIS_SESSION_TIME:  07-05-2019 10:42:37.0760

ANALYSIS_VERSION: 10.0.15063.400 amd64fre

STACK_TEXT:  
ffffd888`902f24b8 fffff807`4ec77669 : 00000000`0000000a fffff807`5e1abae0 00000000`00000002 00000000`00000000 : nt!KeBugCheckEx
ffffd888`902f24c0 fffff807`4ec73a8e : 00000000`656b6f54 ffff8005`f48a4900 00000000`00000000 00000000`00000004 : nt!KiBugCheckDispatch+0x69
ffffd888`902f2600 fffff807`4eb48200 : 00000000`00000000 ffff8006`104e4410 ffffaa0d`869e0d50 00000000`00000002 : nt!KiPageFault+0x44e
ffffd888`902f2790 fffff807`4f0b9217 : ffffaa0d`9024a050 ffffd888`902f2928 ffffaa0d`9024a050 ffff8006`104e4410 : nt!ExInitializeResourceLite+0x90
ffffd888`902f27c0 fffff807`4f0b81eb : 00000000`00000000 00000000`00000001 ffffd888`902f2a00 ffffaa0d`6edcd730 : nt!SepDuplicateToken+0x157
ffffd888`902f28a0 fffff807`4f0b7e11 : ffff8006`1c054080 ffff8006`02000000 ffffaa0d`7d670001 00000000`00000000 : nt!NtOpenThreadTokenEx+0x3cb
ffffd888`902f29c0 fffff807`4ec77085 : ffff8006`1c054080 00000263`07a42350 00000000`00000000 ffffd888`00019b0c : nt!NtOpenThreadToken+0x11
ffffd888`902f2a00 00007ffd`ef1ffbe4 : 00007ffd`ebbbf37b 00000263`07b72770 000000fb`80b7eac8 abababab`dededede : nt!KiSystemServiceCopyEnd+0x25
000000fb`80b7e9e8 00007ffd`ebbbf37b : 00000263`07b72770 000000fb`80b7eac8 abababab`dededede 00000263`0767bd80 : ntdll!NtOpenThreadToken+0x14
000000fb`80b7e9f0 00007ffd`e90b4ef0 : 00000000`00000000 00000000`00000000 00006dd0`00000000 00000000`00000000 : KERNELBASE!OpenThreadToken+0xb
000000fb`80b7ea20 00007ffd`e90aaf92 : 00000000`00000000 000000fb`80b7eac0 00000263`07a42350 00000000`00000000 : rpcss!LookupOrCreateTokenForRPCClient+0x70
000000fb`80b7ea80 00007ffd`ed957803 : 00000263`07a42350 00000263`07ecc2dc 00000000`00000000 00000000`00000000 : rpcss!_QueryNTService+0xb2
000000fb`80b7eba0 00007ffd`ed8f436c : 00007ffd`e9193562 000000fb`80b7f000 00000000`00000007 00007ffd`e9182860 : RPCRT4!Invoke+0x73
000000fb`80b7ec20 00007ffd`ed8f756a : 00000000`00000000 00000000`00000000 00000000`00000000 00007ffd`ef1b1b2d : RPCRT4!NdrStubCall2+0x42c
000000fb`80b7f250 00007ffd`ed934a38 : 006c0069`0046005c 00730079`00000001 00000000`00000000 00000000`00000000 : RPCRT4!NdrServerCall2+0x1a
000000fb`80b7f280 00007ffd`ed9104b0 : 00000000`00000001 00000263`06683310 000000fb`80b7f460 00000263`065b0000 : RPCRT4!DispatchToStubInCNoAvrf+0x18
000000fb`80b7f2d0 00007ffd`ed90fe5b : 00000263`06683310 00000000`00000000 00000263`00000000 00000263`07a424a0 : RPCRT4!RPC_INTERFACE::DispatchToStubWorker+0x1a0
000000fb`80b7f3a0 00007ffd`ed9021ff : 000000fb`80b7f540 00000263`07a42350 00000000`00000000 00000000`00000003 : RPCRT4!RPC_INTERFACE::DispatchToStub+0xcb
000000fb`80b7f400 00007ffd`ed90165a : 00000000`001ea015 00000000`00000001 00000000`00000000 00000263`06631890 : RPCRT4!LRPC_SCALL::DispatchRequest+0x35f
000000fb`80b7f4e0 00007ffd`ed900c21 : 000000fb`80b7f770 00000263`00000000 00000000`00000000 00000000`00000000 : RPCRT4!LRPC_SCALL::HandleRequest+0x7fa
000000fb`80b7f5e0 00007ffd`ed900692 : 00000000`00000000 00000000`00000000 00000000`00000001 00000263`0663e780 : RPCRT4!LRPC_ADDRESS::HandleRequest+0x341
000000fb`80b7f680 00007ffd`ed8f7465 : 000000fb`80b7f879 00000263`07b72770 00000263`0663e888 000000fb`80b7fa48 : RPCRT4!LRPC_ADDRESS::ProcessIO+0x8a2
000000fb`80b7f7c0 00007ffd`ef1af4c0 : 000000fb`80b7f860 00000000`00000000 000000fb`80b7fa48 00000263`06626ac0 : RPCRT4!LrpcIoComplete+0xc5
000000fb`80b7f860 00007ffd`ef1b0348 : 00000000`00000000 00000263`00000000 00000000`00000000 00000000`00000000 : ntdll!TppAlpcpExecuteCallback+0x260
000000fb`80b7f8e0 00007ffd`ed327974 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!TppWorkerThread+0x3c8
000000fb`80b7fbd0 00007ffd`ef1ca271 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : KERNEL32!BaseThreadInitThunk+0x14
000000fb`80b7fc00 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21

**Comment by analyze-v** [comment] 2019-07-11 15:28
Hmm the sysmon driver is called sysmondrv.sys so it's not directly referenced but that doesn't mean it's innocent and it seems a coincidence that this occurred during the uninstall.

Could you contact me offline at syssite@microsoft.com and I will provide you with a location to upload the dump file.

Thanks for reporting this and for offering to assist in tracking down the cause

MarkC (MSFT)

**Comment by yoannwyffels** [comment] 2019-07-12 07:34
Hello MarkC,

thank you for your answer.
In the sysmon command line options, you're able to specify a driver name, that's what we do: sysmon -accepteula -d **psav3cld** -i config.xml.
I'm contacting you offline.

Best regards

**Comment by yoannwyffels** [comment] 2019-07-12 07:38
Hello MarkC,

As I said on GitHub, we had specify a driver name in the sysmon install
command line:
sysmon -accepteula -d psav3cld -i config.xml

That's why you will see psav3cld.sys in the dump file as the sysmon driver.

I can eventually share dump on my web server if you want to, or I can
upload wherever you want.

Many Thanks
Best regards,
Yoann W.

Le jeu. 11 juil. 2019 à 17:28, analyze-v <notifications@github.com> a
écrit :

**Comment by analyze-v** [comment] 2019-07-17 09:51
For anybody else who sees this, it was a known issue in Sysmon 9 that has been resolved in Sysmon 10 and later.

MarkC (MSFT)

**Closed by analyze-v** 2019-07-17 09:51 UTC
