### ISSUE TITLE
[DemoType] ZoomIt64 v8.01 Polish diacritical characters

### ISSUE THREAD

**Issue by milenamilka755** [MicrosoftDocs/sysinternals#789] opened 2024-03-20 16:45 UTC
DemoType feature does not work correctly with Polish diacritical characters ą , ć, ę, ł, ń, ó, ś, ż , ź

**Comment by foxmsft** [comment] 2024-03-20 17:43
Closing, as it's a duplicate of #788

**Closed by foxmsft** 2024-03-20 17:43 UTC
